### ISSUE TITLE
Real world deployment code

### ISSUE THREAD

**Issue by willxxy** [sled-group/RACER#5]
Hello again,

Thanks for the work again. I found, to my knowledge, that the real world deployment code was not provided. 
Are there any plans on providing this? I found it a bit cumbersome to set it up myself due to the simulation environment being deeply embedded into the model code. 

Thank you!

**Comment by YinpeiDai** [comment]
Hi, we follow the original RVT to set up real experiments. Since RVT takes the pointcloud as input, you can just save the pointcloud to generated replay buffers from real scenes to train your model, you may need to set your own SCENE_BOUNDS, TRAINING_ITERATIONS, etc for better configuration.  For evaluation, we use fastapi to set up client-service to call the model.

**Comment by willxxy** [comment]
Ok thank you!
